[package]
name = "rocks_db"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
num_cpus = "1.16.0"
rocksdb = "0.23.0"
#serde = "1.0.219"
serde = { version = "1.0", features = ["derive"] }
